pipeline {
    agent any

    stages {

        stage('checkout2') {
    
                steps {
                    sh "git clone  https://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@github.com/Tanishk-tech/course-jenkins-project.git -b main"
                }
        }

        stage('Setup') {
            steps {
                sh "pip install -r 01-jenkins-basics/requirements.txt"
            }
        }
        stage('Test') {
            steps {
                sh "pytest"
                
            }
        }                
    }
}
